"""

Revision ID: f2ea99ea49a5
Revises: 23b2ef53d378
Create Date: 2025-12-17 22:05:53.146463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ea99ea49a5'
down_revision: Union[str, Sequence[str], None] = '23b2ef53d378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_bot_id'), table_name='users')
    op.drop_constraint(op.f('uq_user_bot'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.drop_column('users', 'bot_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bot_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_unique_constraint(op.f('uq_user_bot'), 'users', ['telegram_id', 'bot_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_bot_id'), 'users', ['bot_id'], unique=False)
    # ### end Alembic commands ###

